### ISSUE TITLE
Overall ToDo List of Management Team

### ISSUE THREAD

**Issue by boggumi** [eunsolkang/review-analysis-web-report#8]
**Describe the goal of this task**
Overall planning team organization

**Write down what you have to do in the form of a checklist**
- [x] Making a team introduction video
- [x] Design PT Flow 
- [x] Naming of our business
- [x] Back Up Business-Related Materials
- [x] PT ( English Scripts & PPT )

**Comment by boggumi** [comment]
Making a team introduction video 
=> was done on 02/13 and submitted on 02/14

**Comment by boggumi** [comment]
Designing PT Flow
=> was done on 21/02/15

**Comment by boggumi** [comment]
Naming of our business
=> was done on 21/02/18
We selected name of our business as "trop.er" and made our unique logo

**Comment by boggumi** [comment]
PT ( English Scripts & PPT )
=> was done on 21/02/21
